language: ruby
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.5.1
    env: PUPPET_VERSION="~> 6.0"
notifications:
  email: 'zan.loy@gmail.com'
