---
dist: trusty
language: ruby
script:
  - "bundle exec rubocop"
  - "bundle exec rake lint"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  include:
  - rvm: 2.1.10
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.1.10
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.4.5
    env: PUPPET_VERSION="~> 5.0"
  - rvm: 2.5.3
    env: PUPPET_VERSION="~> 6.0"
